name: deno

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        deno: [1.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup deno ${{ matrix.deno }}
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno }}
    - run: npm install -g yarn
    - name: install
      run: yarn
    - name: clean
      run: yarn clean
    - name: build
      run: yarn build
    - name: test
      run: "yarn test:deno"
